updating readme [skip ci]

diff --git a/.github/workflows/test-model.yml b/.github/workflows/test-model.yml
--- a/.github/workflows/test-model.yml
+++ b/.github/workflows/test-model.yml
@@ -66,12 +66,16 @@ jobs:
           BRANCH: "main"
           REPO_NAME: ${{ github.event.repository.name }}
           AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
-        run: |
-          source activate
-          echo "Updating metadata to AirTable looking at owner: $USER_NAME"
-          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/update_metadata_to_airtable.py
-          python3 update_metadata_to_airtable.py $USER_NAME $REPO_NAME $BRANCH $AIRTABLE_API_KEY
-          rm update_metadata_to_airtable.py
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          command: |
+            source activate
+            echo "Updating metadata to AirTable looking at owner: $USER_NAME"
+            wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/update_metadata_to_airtable.py
+            python3 update_metadata_to_airtable.py $USER_NAME $REPO_NAME $BRANCH $AIRTABLE_API_KEY
+            rm update_metadata_to_airtable.py
 
       - name: Update README file
         id: update-readme-file
@@ -96,22 +100,44 @@ jobs:
           amend: true
           force: true
       
-      - name: Predict output
+      - name: Fetch model
         env:
           MODEL_ID: ${{ github.event.repository.name }}
         run: |
-          source activate
-          echo "Sample model id selected: $MODEL_ID"
-          ersilia -v fetch $MODEL_ID --repo_path .
-          ersilia -v serve $MODEL_ID
-          ersilia sample -n 5 -f input.csv
-          ersilia -v api -i input.csv
-          ersilia close
+            source activate
+            ersilia -v fetch $MODEL_ID --repo_path .
+            FOLDER="$HOME/eos/repository/$MODEL_ID"
+            if [ ! -d "$FOLDER" ]; then
+              echo "Error: Folder '$FOLDER' does not exist." >&2
+              exit 1
+            fi
           
+      - name: Serve model
+        env:
+          MODEL_ID: ${{ github.event.repository.name }}
+        run: |
+            source activate
+            ersilia -v serve $MODEL_ID
+
+      - name: Test model
+        env:
+          MODEL_ID: ${{ github.event.repository.name }}
+        run: |
+            source activate
+            ersilia example -n 5 -f input.csv --predefined
+            ersilia -v run -i "input.csv" -o "output.csv"
+            ersilia close
+            output=$(python .github/scripts/verify_model_outcome.py output.csv)
+            if echo "$output" | grep -q "All outcomes are null"; then
+              echo "Error in model outcome, aborting test"
+              exit 1
+            fi
+            rm output.csv
+
       - name: Upload log output
+        if: always()
         uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb #pin v3.1.1
         with:
           name: debug-logs
-          retention-days: 1
-          path: /home/runner/eos/console.log
-
+          retention-days: 14
+          path: /home/runner/eos/*.log
